### ISSUE TITLE
Support for Type Alias

### ISSUE THREAD

**Issue by pscott** [Shard-Labs/starknet-hardhat-plugin#103]
Cairo-lang [0.8.0](https://github.com/starkware-libs/cairo-lang/releases/tag/v0.8.0) added [Type Aliases](https://cairo-lang.org/docs/how_cairo_works/types.html#used-defined-type-aliases) but it looks like this plugin does not allow one to actually use them :(

Here's a code example that uses it. Try running it, you should have 
```
HardhatPluginError: Expected address to be a tuple
```

https://gist.github.com/pscott/5ac165dd35cd0a4ef55cddf77dda4d05

The way I would expect to call a type alias is this way:
```ts
// Assuming we have `using Foo = (bar: felt, zoro: felt)`, then in ts I would expect
[{bar: 1}, {zoro: 2}]
```
But this is just an idea, might not be the best way to call use it :)

**Comment by FabijanC** [comment]
You are right, it is not supported. However the error I'm getting is:
```
HardhatPluginError: Type address : felt not present in ABI.
```
