### ISSUE TITLE
Argent Account not working in js

### ISSUE THREAD

**Issue by jrcarlos2000** [Shard-Labs/starknet-hardhat-plugin#117]
deploying an Argent account and invoking a function works well 
but when reading an existing account and invoking a function in a contract there this issue :

var msgSignature = keyPair.sign(fixMessage(msgHash));
                             ^
TypeError: Cannot read properties of null (reading 'sign')

using the private key exported from argent google extension 

<img width="637" alt="Screen Shot 2022-06-06 at 7 02 37 PM" src="https://user-images.githubusercontent.com/88168831/172148890-ebce88ae-9dc6-4415-b1ae-7a562e1d53d8.png">

**Comment by badurinantun** [comment]
What is the format of the private key?

**Comment by jrcarlos2000** [comment]
> What is the format of the private key?

Is a hex string , from argent google extension casted to hex

**Comment by badurinantun** [comment]
I'm not sure why it's `null`, are you sure `process.env.PRIVATE_KEY` is set?

**Comment by jrcarlos2000** [comment]
Private key is set

**Comment by badurinantun** [comment]
Was this Argent account deployed using the Hardhat plugin?

**Comment by badurinantun** [comment]
Artifacts probably don't match, you would need to deploy the exact contract that was deployed previously

**Comment by rzmahmood** [comment]
Also having this exact same issue

**Comment by FabijanC** [comment]
When you deploy your Argent Account, also store its guardian key. Then next time when you are loading it with `starknet.getAccountFromAddress`, also set the guardian:
```typescript
const deployedAccount = await starknet.deployAccount("Argent");
const address = deployedAccount.address;
const privateKey = deployedAccount.privatekey;
const guardianPrivatekey = deployedAccount.guardianPrivateKey;

... doStuffHere() ...

const loadedAccount = (await starknet.getAccountFromAddress(address, privateKey, "Argent")) as ArgentAccount;
await loadedAccount.setGuardian(guardianPrivateKey);
```

Note that deploying ArgentAccounts currently (v0.5.5) only works on Devnet because internally this requires invoking the `initialize` method of the account contract, which incurs cost (and requires a fee). Future versions will probably separate the initialization from the deployment.

**Comment by rzmahmood** [comment]
What is my Argent Account uses the 0 address as the guardian key? I'm still having this issue

**Comment by FabijanC** [comment]
> What if my Argent Account uses the 0 address as the guardian key? This is the default used by ArgentX. I'm still having this issue

This will be fixed in the next plugin version.
