### ISSUE TITLE
Export all flag

### ISSUE THREAD

**Issue by ssteiger** [Shard-Labs/starknet-hardhat-plugin#121]
Hey! Thanks for creating this package. It has really helped me a lot!

Quick question: 
Is there an `--export-all ../react-app/src/contracts/hardhat_contracts.json"` flag like the ethereum hardhat package has?
Or is there a way to output a json file with an array of all deployed contracts with their respective addresses and ABI's?

**Comment by ssteiger** [comment]
Ahh - lol no it's not.
It's a [hardhat-deploy](https://github.com/wighawag/hardhat-deploy) feature.
My bad. I'll see if I can get it to work when combining the two plugins.

**Comment by FabijanC** [comment]
There have been requests to integrate this plugin with the `hardhat-deploy` plugin, do you know how that could be done?

**Comment by ssteiger** [comment]
Not sure. I'll look into it.

**Comment by FabijanC** [comment]
@ssteiger Any feedback?

**Comment by ssteiger** [comment]
I've created a dirty workaround script in my project for now [here](https://github.com/ssteiger/starknet-dapp-boilerplate/blob/main/packages/hardhat/deploy/00_deploy_your_contract.js#L81).
The starknet-hardhat-plugin has seen a lot of changes in the past week. I'll continue working on it and will post here once I have something neat that is working.

**Comment by ssteiger** [comment]
An idea would be to wrap this into its own `publish.js` script that goes into the `postdeploy` hook. eg  

`"postdeploy": "hardhat run scripts/publish.js",`

It would be neater ofc. if [hardhat-deploy](https://github.com/wighawag/hardhat-deploy) did this directly like it does with solidity.

**Comment by FabijanC** [comment]
This is a candidate for closing. Any feedback @ssteiger ?

**Comment by FabijanC** [comment]
Closing as stale
