### ISSUE TITLE
Cannot deploy Argent Account

### ISSUE THREAD

**Issue by rzmahmood** [Shard-Labs/starknet-hardhat-plugin#127]
```js
const starknetAccount = await starknet.deployAccount("OpenZeppelin");
```
This fails with error:

```sh
HardhatPluginError: Could not perform invoke on initialize:
Got BadRequest while trying to access https://alpha4.starknet.io/gateway/add_transaction. Status code: 500; text: {"code": "StarknetErrorCode.OUT_OF_RANGE_FEE", "message": "max_fee must be bigger than 0.\n0 >= 0"}.
```

I believe it's because a fee is required to initialize the Argent Account, but I can't set a fee using `await starknet.deployAccount("OpenZeppelin");`

This is mentioned here: https://github.com/Shard-Labs/starknet-hardhat-plugin/issues/117#issuecomment-1158566007
But should be trakced imo

**Comment by FabijanC** [comment]
Your code snippet says `"OpenZeppelin"` but I assume you mean `"Argent"`.

This should be fixed with the next plugin version.
