### ISSUE TITLE
Add plugin support for default entrypoints

### ISSUE THREAD

**Issue by ivpavici** [Shard-Labs/starknet-hardhat-plugin#151]
Some users would like to use the plugin as the proxy for default entrypoints in other contracts. it should be doable if when checking the function in the abi, if it doesn't exist, return `__default__` instead of an error

**Comment by FabijanC** [comment]
Related issue: https://github.com/Shard-Labs/starknet-hardhat-plugin/issues/137
In the same issue, a solution was proposed: https://github.com/Shard-Labs/starknet-hardhat-plugin/issues/137#issuecomment-1178841412.
Temporary solution is to set `proxy.abi` and `proxy.abiPath` to the corresponding properties of the implementation contract (although with `@ts-ignore`).
Long term solution would be to introduce a custom method for this.
