### ISSUE TITLE
OpenZeppeling 0.2.0 account contract have an issue with signature verification.

### ISSUE THREAD

**Issue by amanusk** [Shard-Labs/starknet-hardhat-plugin#161]
I have tried running the `oz-account-test.ts` test of `starknet-plugin-exaple` and ran into the following issue:
```

  2) OpenZeppelin account
       should handle multiple invokes through an account:
     Error: Transaction rejected. Error message:

Error at pc=0:133:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:746)
Unknown location (pc=0:682)
Error message: Account: invalid signature
Unknown location (pc=0:347)
Unknown location (pc=0:321)

Traceback (most recent call last):
  File "<hint14>", line 1, in <module>
  File "/app/src/starkware/starknet/services/batcher/starknet_batcher_venv-site/starkware/cairo/lang/builtins/signature/signature_builtin_runner.py", line 94, in add_signature
    ), f"Signature hint must point to the signature builtin segment, not {addr}."
AssertionError: Signature hint must point to the signature builtin segment, not 14:0.
```

The cause is probably this issue [#378](https://github.com/OpenZeppelin/cairo-contracts/pull/387#issuecomment-1183208148) of OpenZeppelin with contracts of version 0.2.0 on Goerli testnet.

**Comment by FabijanC** [comment]
So it happens only on alpha-goerli? Not on Devnet? Should it be fixed with the newly released OZ v0.2.1?

I still don't really understand what's the issue here.

**Comment by amanusk** [comment]
That's my understanding, yes.
Only happens on alpha-goerli.
A fix was already merged, I assume it will be available in the next version.

This can be used to track the fix here.

**Comment by archseer** [comment]
I'd recommend fixing this to address https://github.com/OpenZeppelin/cairo-contracts/issues/344 too
