### ISSUE TITLE
Module '"hardhat"' has no exported member 'starknet'

### ISSUE THREAD

**Issue by parketh** [Shard-Labs/starknet-hardhat-plugin#166]
When including `import { starknet } from "hardhat"` at the top of my `index.tsx` file I get the error:

```
Module '"hardhat"' has no exported member 'starknet'
```

The module is not importing correctly as I get a bunch of messages saying the modules cannot be resolved. The code runs fine with Node.js just not with React for some reason. Anyone know why?

Here are my `hardhat.config.ts` settings:

```
const { HardhatUserConfig } = require("hardhat/types")
require("@shardlabs/starknet-hardhat-plugin")
require("@nomiclabs/hardhat-ethers")

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
    solidity: "0.8.9",
    starknet: {
        venv: "cairo_venv",
        network: "devnet",
        wallets: {
            OpenZeppelin: {
                accountName: "OpenZeppelin",
                modulePath: "starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount",
                accountPath: "~/.starknet_accounts",
            },
        },
    },
    networks: {
        devnet: {
            url: "http://127.0.0.1:5050",
        },
    },
}

```

**Comment by FabijanC** [comment]
Hardhat is a developer tool and isn't meant to be run in a browser (basically a node-only tool from my understanding). And starknet-hardhat-plugin is just a plugin for hardhat.

What would help is to have the contract-interaction part of the plugin extracted to a separate npm package which wouldn't be hardhat- or node-dependent. This is currently not in the plans, but might change in the future.

**Comment by parketh** [comment]
Thanks, that makes sense. I ended up running it in node.js as an express server and accessing via a fetch request, works fine for now until there is an easier way!
