### ISSUE TITLE
Create Github pages for this repo

### ISSUE THREAD

**Issue by ivpavici** [Shard-Labs/starknet-hardhat-plugin#177]
Docusaurus could be used.
Example: https://shard-labs.github.io/starknet-devnet/

**Comment by shramee** [comment]
Happy to work on this.

**Comment by FabijanC** [comment]
Hi @shramee and thanks for your interest - I assigned you. I guess it should be enough to cover README.md, and not README-dev.md, wdyt @ivpavici?

**Comment by ivpavici** [comment]
We can add both, why not, README-dev.md can be under a page called Guides, or something?
@shramee you can take a look at https://www.starknetjs.com/ , it's using Docusaurus

**Comment by shramee** [comment]
Apologies for the delay on this one guys,
Here's a preview - https://shramee.github.io/starknet-hardhat-plugin/

Deployment,
```sh
cd www
npm install
USE_SSH=true npm run deploy
```

**Comment by ivpavici** [comment]
looks good, only questions is do we keep it all in one page, or break into multiple pages? wdyt @FabijanC  ?

**Comment by FabijanC** [comment]
@ivpavici I think having it like this makes searching easier. Thanks @shramee
