### ISSUE TITLE
Breaking changes in 0.6.3

### ISSUE THREAD

**Issue by pscott** [Shard-Labs/starknet-hardhat-plugin#189]
# Description

I recently updated my `starknet-hardhat-plugin` to use `0.6.3` and found that it introduced some breaking changes (not on all machines I think).

# Error

The error is this one:
```
     HardhatPluginError: starknet-venv-proxy connect exited with code=1:
  File "/Users/Code/my_example/node_modules/@shardlabs/starknet-hardhat-plugin/dist/src/starknet_cli_wrapper.py", line 25
    async def _execute(self):
            ^
SyntaxError: invalid syntax

      at ChildProcess.<anonymous> (node_modules/@shardlabs/starknet-hardhat-plugin/src/devnet/external-server.ts:128:32)
      at ChildProcess.emit (node:events:520:28)
      at ChildProcess.emit (node:domain:475:12)
      at maybeClose (node:internal/child_process:1092:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

# Reproducing

When running the command `npx hardhat test` with this single test:
```ts
import { starknet } from "hardhat";

describe("Starknet", function () {
    it("works", async function () {
        const controller = await starknet.deployAccount('OpenZeppelin');
    });
});
```
# Additional information
- I'm using the `venv: active` (meaning I'm not using any `venv` at all).
- To debug that, I identified that the syntax error probably had to do with a `python` vs `python3` problem (indeed python reports a syntax error when python3 runs fine).
- On my machine, `python` refers to `python2.7` and python3 to `python3.8.9` (this is probably the case on a lot of machines which still need to have python refert to python2.7 for old apps
- I'm guessingn `0.6.3` introduced some changes which call `python` instead of `python3` (or something similar?) and this is what is getting me into trouble :) When I revert back to `0.6.2`, everything works fine :)

**Comment by FabijanC** [comment]
Thanks for the thorough bug report!

Actually 0.6.3 introduced an optimization that runs all starknet commands through a proxy server - previously the `starknet` and `starknet-compile` commands were used directly, now the `python` command is used to run that server.

You should really give it a try as it speeds things up significantly. Until a fix version is released, you can just link your `python` command to point to `python3`.

**Comment by pscott** [comment]
So I tried linking python to python3 but:
- a simple alias won't work (as it's not ran through the shell.. so it needs to be a symlink)
- a symlink could break other apps on my computer...


I think in an ideal scenario, I could do something like `python_path` in my config, and this would be the path used for `python`. Wdyt? :)

**Comment by FabijanC** [comment]
Or you can create a python3 virtual environment with cairo-lang installed, then you can just put the path under `venv` in your hardhat config.

**Comment by FabijanC** [comment]
Btw, did you check this: https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3
Don't know which OS you're on, but they mention your concern about breaking other apps, as well as a workaround (basically installing `python-is-python3`)

**Comment by pscott** [comment]
> Or you can create a python3 virtual environment with cairo-lang installed, then you can just put the path under `venv` in your hardhat config.

Yeah reality of it is I don't like using venv because I always get confused :p I just prefer running things natively. But ok I guess I will need to run a python venv starting from now! :) thanks :D

**Comment by FabijanC** [comment]
Plugin v0.6.4 uses `python3`, did you try it out?

**Comment by pscott** [comment]
> Plugin v0.6.4 uses `python3`, did you try it out?

Just tried it out, it's working on my machine! Thanks! :)
