### ISSUE TITLE
Document debugging possibility

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-hardhat-plugin#200]
Make mention of printing in hints, compiling with hint validation disabled, using integrated-devnet stdout.
Consider this for reference: https://github.com/Shard-Labs/starknet-devnet/#contract-debugging
Also potentially find where this was explained in the Telegram starknet core stars group

**Comment by shramee** [comment]
Happy to get on with this one next before I get on to beefier and exciting stuff.

**Comment by shramee** [comment]
Here's the copy,

## Debugging contracts

To debug StarkNet contracts, you can use `print()` in cairo hints in your contract, and the printed lines will appear in Devnet's log.

For example, when calling the following `increase_balance` with input `25`.

```cairo
@external
func increase_balance{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
    amount: felt
) {
    let (res) = balance.read();
    %{ print( "Adding balance..." ) %}
    %{ print( ids.res ) %}
    balance.write(res + amount);
    let (afterUpdate) = balance.read();
    %{ print( ids.afterUpdate ) %}
    return ();
}
```

DevNet logs look like this,

```
Adding balance...
0
25
```

When using `integrated-devnet` you can specify `stdout` as `STDOUT` or a file in your hardhat config file. Documented in [runtime network](#runtime-network---integrated-devnet) section.

**Comment by shramee** [comment]
Final copy,

## Debugging contracts

To debug StarkNet contracts, you can use `print()` in cairo hints in your contract, and the printed lines will appear in Devnet's log.

Compile with `--disable-hint-validation` flag to allow hints.

```
$ hardhat starknet-compile --disable-hint-validation
```

For example, when calling the following `increase_balance` with input `25`.

```cairo
@external
func increase_balance{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
    amount: felt
) {
    let (res) = balance.read();
    %{ print( "Adding balance..." ) %}
    %{ print( ids.res ) %}
    balance.write(res + amount);
    let (afterUpdate) = balance.read();
    %{ print( ids.afterUpdate ) %}
    return ();
}
```

DevNet logs look like this,

```
Adding balance...
0
25
```

When using `integrated-devnet` you can specify `stdout` as `STDOUT` or a file in your hardhat config file. Documented in [runtime network](#runtime-network---integrated-devnet) section.
