### ISSUE TITLE
Use existing Python virtual environment?

### ISSUE THREAD

**Issue by delaaxe** [Shard-Labs/starknet-hardhat-plugin#21]
Could it be possible to configure this plugin to use an existing virtualenv?

This would avoid having to use a heavy container in places where it isn't needed, and also keeps the Python environment accessible for projects that need it (like VSCode plugins)? Starkware is also closely tied to Python and its standard lib and it may prove cumbersome to have it all in a container

**Comment by FabijanC** [comment]
I don't see why it wouldn't be possible. Thanks for the suggestion! It probably won't be included in the next version, though.
