### ISSUE TITLE
Declaring class hash fails 

### ISSUE THREAD

**Issue by hsouf** [Shard-Labs/starknet-hardhat-plugin#211]
I might be missing out on something but I'm getting the following error:

`StarknetPluginError: Could not declare class: Error: AssertionError: Sender must be passed explicitly when making a direct declaration using --no_wallet.`

After running: 

 ```
const l2BridgeFactory = await starknet.getContractFactory("bridge");
const  l2BridgeImplHash = await l2BridgeFactory.declare(); //<--->getting error at this level
```

My current setup:
- python = "^3.9"
- cairo-lang = "^0.10.0"
- starknet-devnet = "^0.3.0"

**Comment by FabijanC** [comment]
I assume you are using the partially adapted plugin version `0.6.6-alpha.0`. If so, thank you for testing it! If not, try it out. If you are unsure about the exact installed version, you can run `npx hardhat starknet-plugin-version`.

Plugin is still undergoing adaptation to Starknet v0.10.0, and fixing this will be included.

**Comment by hsouf** [comment]
Yes! I'm using the version `0.6.6-alpha.0`
