### ISSUE TITLE
StarknetErrorCode.OUT_OF_RANGE_FEE for class declaration

### ISSUE THREAD

**Issue by hsouf** [Shard-Labs/starknet-hardhat-plugin#217]
Trying to declare my contract class on Goerli using: 
`const bridgeImplHash = await deployer.declare(L2BridgeFactory, {maxFee: 1e18});`

Results in the following error 

`StarknetPluginError: Could not declare class: Got BadRequest while trying to access https://alpha4.starknet.io/gateway/add_transaction. Status code: 500; text: {"code": "StarknetErrorCode.OUT_OF_RANGE_FEE", "message": "max_fee must be bigger than 0.\n0 >= 0"}.`

@FabijanC

**Comment by FabijanC** [comment]
Seems like the max fee is not being sent properly, thanks for reporting, will fix ASAP
