### ISSUE TITLE
Invoke fails when using proxy contract

### ISSUE THREAD

**Issue by boukestam-allianceblock** [Shard-Labs/starknet-hardhat-plugin#225]
**Our situation:**
We are using a proxy contract to make our implementation upgradable. This means we have one central contract and several implementation (facet) contracts that are being declared and used with library calls from the fallback function in the central contract.

**Problem:**
The AdaptInput function is called for every invoke. On [this line](https://github.com/Shard-Labs/starknet-hardhat-plugin/blob/48d89ac0685024084f2c447e45ffcd9d39dee859/src/types.ts#L723) there is an error thrown whenever the function is not found within the ABI. This is always the case for us, because the central contract's ABI only contains the fallback function that handles the proxying and a function to add a new facet.

**Comment by FabijanC** [comment]
Is this of any help?
https://github.com/Shard-Labs/starknet-hardhat-plugin#delegate-proxy
https://github.com/Shard-Labs/starknet-hardhat-example/blob/master/scripts/delegate-proxy.ts

**Comment by boukestam-allianceblock** [comment]
Thanks for the quick reply! That is super helpful, I don't know how I missed that. The only small problem is we have multiple implementation contracts, and the `setImplementation` function can only set one ABI. But for now I can work around that by creating multiple copies or just changing it before every invoke call.
