### ISSUE TITLE
`config.starknet.network` will overwrite `starknet-network` positional argument

### ISSUE THREAD

**Issue by 0xSidius** [Shard-Labs/starknet-hardhat-plugin#226]
@FabijanC populating the `starknet.network` key in the Hardhat config will cause this plugin to ignore all network positional args, forcefully overriding them. 

Furthermore, commenting out the same setting apparently causes the plugin to always use fallback on a live network, instead of `integrated-devnet`.

**Comment by FabijanC** [comment]
Related: #212

**Comment by 0xSidius** [comment]
@Nathan-SL @FabijanC an update to help reproduce this... given the config below, currently:

- specifying a valid `starknet.network` value in HardhatConfig always overrides any `--starknet-network` pos argument
- given the following example cmd `hardhat run scripts/deploy_accounts.ts --starknet-network starknet-testnet`:
   - will result in Hardhat
(and the plugin) loading the right network, i.e. `Using network starknet-testnet at https://alpha4.starknet.io`
   - causes the plugin to use the local endpoint, which raises this error: `StarknetPluginError: Could not deploy contract: Got ClientConnectorError while trying to access http://127.0.0.1:5050/gateway/add_transaction.`
   - if I comment the `starknet.network` config key, then it fails with: `StarknetPluginError: Request failed. Make sure your network has the /predeployed_accounts endpoint`, apparently the starknet network is treated like a non-live network and fallbacks to integrated-devnet

Imo, the current Starknet networks management system does not work well alongside Hardhat native networks

![image](https://user-images.githubusercontent.com/100469911/195329664-d21fe756-ba9b-4aaf-b505-bcdac4a1724e.png)

**Comment by FabijanC** [comment]
Currently (plugin v0.6.7), `hardhat run` should be used without `--starknet-network`, it doesn't work just as it didn't work and was removed in #74. Basically it never worked, but since we forgot about having this same issue and since this feature was not properly tested, we reintroduced it.

**Comment by FabijanC** [comment]
Solution proposals:
- Store network choice in a file
- Rely on environment variables
