### ISSUE TITLE
Is there any plans to support forking alpha goerli or mainnet?

### ISSUE THREAD

**Issue by 0xHyoga** [Shard-Labs/starknet-hardhat-plugin#229]
It's very helpful specially when integrating with outside contracts which are complex. For example being able to do:

```
hh node --fork {alpha-goerli}
```

**Comment by ivpavici** [comment]
Hi! This is currently not very easy to do, but will be possible in a couple of new Cairo releases. https://github.com/Shard-Labs/starknet-devnet/issues/18#issuecomment-1182961649
