### ISSUE TITLE
starknet-invoke cli command not updating storage in contract

### ISSUE THREAD

**Issue by Nathan-SL** [Shard-Labs/starknet-hardhat-plugin#230]
`starknet-invoke` has no effect on storgae (balance) after a successful transaction. 
```bash
set -e
NETWORK=alpha-goerli
INITIAL_VALUE=10

output=$(npx hardhat starknet-deploy starknet-artifacts/contracts/contract.cairo/ --starknet-network "$NETWORK" --inputs "$INITIAL_VALUE" --wait)
tail=${output#*$'\n'Contract address: }
address=${tail%%$'\n'*}
echo Contract address: "$address"
npx hardhat starknet-invoke --starknet-network "$NETWORK" --contract contract --function increase_balance --address "$address"  --inputs "10 20" --wallet OpenZeppelin
npx hardhat starknet-call --starknet-network "$NETWORK" --contract contract --function get_balance --address "$address"
```

`starknet-call` should return `40` but returns `10`

**Comment by ivpavici** [comment]
https://github.com/starkware-libs/cairo-lang/issues/101

**Comment by FabijanC** [comment]
> [starkware-libs/cairo-lang#101](https://github.com/starkware-libs/cairo-lang/issues/101)

I took a look at this linked issue, I think it's explained by https://github.com/OpenZeppelin/cairo-contracts/issues/471

**Comment by FabijanC** [comment]
What was the conclusion about this? Was invoking attempted with an account that was not deployed/funded? If so, it's not really an issue with the plugin. If someone can confirm, the issue can be closed. Otherwise further investigation needs to be done.
