### ISSUE TITLE
hardhat starknet-compile unfinished artifact

### ISSUE THREAD

**Issue by Orland0x** [Shard-Labs/starknet-hardhat-plugin#234]
When compiling a contract with `hardhat starknet-compile`, the resulting abi file is unfinished (it just cuts off half way though). Using the standard cairo compiler directly works fine. 

Here is the cairo file that wont compile: 
https://github.com/snapshot-labs/sx-core/blob/comments/contracts/starknet/SpaceAccount.cairo

Relevant Discord thread: [link](https://discord.com/channels/793094838509764618/1030059805454385183)

**Comment by solimander** [comment]
Randomly seeing the same behavior, except it's the output file that's unfinished.

**Comment by FabijanC** [comment]
Does it happen for both `dockerizedVersion` and `venv` mode of the hardhat plugin? I'm referring to [this config part](https://github.com/Shard-Labs/starknet-hardhat-plugin/#configure-the-plugin).

**Comment by Orland0x** [comment]
This seems to have resolved itself for me

**Comment by solimander** [comment]
> Does it happen for both dockerizedVersion and venv mode of the hardhat plugin? I'm referring to [this config part](https://github.com/Shard-Labs/starknet-hardhat-plugin/#configure-the-plugin).

Yes, it happens in both modes. I'm about to update to Cairo v0.10.0. I'll let you know if that changes anything.
