### ISSUE TITLE
Dump should always work

### ISSUE THREAD

**Issue by EvolveArt** [Shard-Labs/starknet-hardhat-plugin#238]
While working with hardhat tests I sometimes randomly stumble upon the following error message 
`StarknetPluginError: Request failed. Make sure your network has the /dump endpoint`

This can happen pretty much anytime.

Another (maybe related) issue is that sometimes I have to switch the port of `starknet-devnet` otherwise it says that a connection is still running on this port.

**Comment by FabijanC** [comment]
Are you using integrated-devnet?

**Comment by EvolveArt** [comment]
> Are you using integrated-devnet?

Yes, looks like it works when I use `active` venv
