### ISSUE TITLE
Have `getContractFactory` also fetch and compile contracts in node_modules

### ISSUE THREAD

**Issue by NIC619** [Shard-Labs/starknet-hardhat-plugin#270]
Currently `starknet.getContractFactory` only looks for compiled artifacts. If one needs for example, an `ERC20Mintable` contract from Openzeppelin, he needs to copy the contract to his contract folder and compile it himself. It would be very convenient if `starknet.getContractFactory` can also look for contract downloaded in `node_modules` and compile it itself.

**Comment by FabijanC** [comment]
What I am saying doesn't completely address your proposal, but consider the following:
1. `getContractFactory` can do relative imports:
    - So you can theoretically import form outside of your repo. 
    - [example link](https://github.com/Shard-Labs/starknet-hardhat-example/blob/8992d37c12cfdcac98820a418410cf85839c100f/test/relative-artifacts.test.ts)
2. https://github.com/Shard-Labs/starknet-hardhat-plugin/#installing-third-party-libraries

Btw does OZ have an npm module? I only found a pypi module: https://pypi.org/project/openzeppelin-cairo-contracts/

**Comment by NIC619** [comment]
Yeah we install the OZ following the 3rd party installations guide:
```bash
> yarn add openzeppelin__cairo_contracts@git+https://git@github.com/OpenZeppelin/cairo-contracts.git#v0.5.1
```

Then in hardhat config:
```typescript
    paths: {
        cairoPaths: ["./node_modules/openzeppelin__cairo_contracts/src"],
    },
```

Is it possible that the plugin also search for contracts in directories specified by `cairoPaths`?

**Comment by FabijanC** [comment]
The following worked for me (no changes to `hardhat.config.ts`):
Install
```
yarn add openzeppelin__cairo_contracts@git+https://git@github.com/OpenZeppelin/cairo-contracts.git#v0.5.1
```

Compile
```
npx hardhat starknet-compile node_modules/openzeppelin__cairo_contracts/src/openzeppelin/token/erc20/presets/ERC20.cairo
```

In a Mocha test I do:
```typescript
await starknet.getContractFactory(
  "node_modules/openzeppelin__cairo_contracts/src/openzeppelin/token/erc20/presets/ERC20"
);
```

**Comment by FabijanC** [comment]
Btw is this a thing - if you want to include a github repo locally?
- If you're using npm the repo has to be an npm module (i.e. it must have `package.json`)
- Otherwise you have to use `yarn`

**Comment by NIC619** [comment]
Yeah, we have been using `yarn add`.

This is currently our workaround:
```typescript
export async function getThirdPartyContractFactory(pathToContract: string) {
    // Append ".cairo" to path if it does not end with ".cairo"
    pathToContract = pathToContract.endsWith(".cairo") ? pathToContract : pathToContract + ".cairo"
    let contractFactory: StarknetContractFactory
    try {
        contractFactory = await starknet.getContractFactory(pathToContract)
    } catch (error) {
        await hardhatStarknetCompile([pathToContract])
        contractFactory = await starknet.getContractFactory(pathToContract)
    }
    return contractFactory
}

...

const tokenFactory = await getThirdPartyContractFactory(
    "node_modules/openzeppelin__cairo_contracts/src/openzeppelin/token/erc20/presets/ERC20Mintable",
)
```

`hardhatStarknetCompile` is copied from https://github.com/Shard-Labs/starknet-hardhat-plugin/blob/2c823d0447cd3f739bdfadb078115e50a4e3bdb7/test/utils/cli-functions.ts#L16

**Comment by FabijanC** [comment]
Ok, nice workaround! I would even suggest compiling like this:
```
```
