### ISSUE TITLE
Add `starknet.devnet.mint` utility

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-hardhat-plugin#272]
Similar to other existing `starknet.devnet` utilities.

This change should be reflected in [our example repo](https://github.com/Shard-Labs/starknet-hardhat-example) since there we currently use a custom function for this: https://github.com/Shard-Labs/starknet-hardhat-example/blob/4d8e7e54bc1d79646e3cc238b0e5190661273535/test/util.ts#L51

**Comment by shramee** [comment]
Happy to work on this next.
