### ISSUE TITLE
Allow running integrated-devnet with Rust VM

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-hardhat-plugin#301]
Users should be able to specify which VM they want.

The env var needs to be passed: https://shard-labs.github.io/starknet-devnet/docs/guide/run#run-with-the-rust-implementation-of-cairo-vm

This should be simply implementable for both dockerized and installed integrated-devnet.

**Comment by notV4l** [comment]
I started working on this issue today.
