### ISSUE TITLE
Class declaration should return transaction hash instead of class hash

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-hardhat-plugin#313]
Rationale:
- class hash can be retrieved in other ways (`contractFactory.getClassHash()`)
- there is no way of getting the transaction hash if it failed

This would be a breaking change.

**Comment by remiroyc** [comment]
Hey @FabijanC as mentioned during our discussion, I'd like to try to fix this issue

**Comment by TsBauer** [comment]
Hey there, I'd love to tackle this issue
