### ISSUE TITLE
WSL issues

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-hardhat-plugin#321]
WSL might not be completely compatible with the plugin.

Can host.docker.internal be used on Linux? Handling localhost uniformly would simplify the code and potentially prevent issues.
Possible solution, didn't get it to work locally on my Linux machine: https://stackoverflow.com/questions/30109037/how-can-i-forward-localhost-port-on-my-container-to-localhost-on-my-host

**Comment by notV4l** [comment]
i may have solution for wsl/docker desktop users
