### ISSUE TITLE
`starknet-deploy` should support `salt` parameter

### ISSUE THREAD

**Issue by maciejka** [Shard-Labs/starknet-hardhat-plugin#40]
Python CLI deploy command supports `salt` parameter:
```
(cairo_venv) maciejka@X1$ starknet deploy
usage: starknet [-h] [--salt SALT] [--inputs [INPUTS [INPUTS ...]]] --contract
                CONTRACT [--token TOKEN]
starknet: error: the following arguments are required: --contract
```
hardhat plug in does not seem to do it: https://github.com/Shard-Labs/starknet-hardhat-plugin/blob/1bd7c2a34198155e95137849fcf36536c296d4e6/src/starknet-wrappers.ts#L17

`Deploy` method of `StarknetContractFactory` (https://github.com/Shard-Labs/starknet-hardhat-plugin/blob/1bd7c2a34198155e95137849fcf36536c296d4e6/src/types.ts#L163) should also support this parameter.

**Comment by FabijanC** [comment]
Makes sense, thanks for suggesting this, hopefully it will be included in the next version.
