### ISSUE TITLE
Cannot deploy account

### ISSUE THREAD

**Issue by ccarnino** [Shard-Labs/starknet-hardhat-plugin#63]
Hello team.

I am trying to simply deploy a new account wallet. But I get a dependency issue error:
```
> yarn hardhat starknet-deploy-account --starknet-network devnet --wallet Deployer
yarn run v1.22.17
$ /Users/claudio/Dev/web3/starknet-erc721-homeworks/node_modules/.bin/hardhat starknet-deploy-account --starknet-network devnet --wallet Deployer
Starknet plugin using the active environment.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named asyncio

        Failed

Error in plugin Starknet: Could not deploy account contract:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named asyncio


For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is a working installation (I can compile and deploy contracts). And `Deployer` is a correct wallet defined in the `hardhat.config.ts`.

**Comment by FabijanC** [comment]
So I see you're using the active environment option.

1. What's your Python version in that environment? 
2. What do you get if you run the following line in that environment:
```
python -c "import asyncio; print(asyncio)"
```

**Comment by ccarnino** [comment]
I am using python 3.9 usually. But I am on macOS which has installed both 2.7 and 3.9. So just writing `python` does not work. I have to specify which version.

You can see it exactly running your command:
```
❯ python -c "import asyncio; print(asyncio)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named asyncio
~/Dev/web3/starknet-erc721-homeworks dev* ⇡ ❯ python3 -c "import asyncio; print(asyncio)"
<module 'asyncio' from '/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/__init__.py'>
```

**Comment by ccarnino** [comment]
Let me correct. On macOS when `python --version` is `Python 2.7.18`. So the problem is that the default python is the wrong one.

**Comment by FabijanC** [comment]
Do you have a virtual environment installed?
You can install one with `python3 -m venv /path/to/my_venv`.
If you can't use venv, there are other tools like pyenv.
Then you can either:
- activate it with `source ~/venvs/my_venv/bin/activate` and keep the `"venv: "active"` configuration in hardhat.config
- set `"venv": "/path/to/my_venv"` in hardhat.config
In either case, you should install `cairo-lang` in the venv you plan to use.

The above approach will work if the virtual environment generated by venv introduces a `python` command which is `python3`.

**Comment by ccarnino** [comment]
Ok, very good point. Now I created a venv in the project folder and activated it. So it is using python3 in the project.
Now everything works as intended! Thanks for the support.
