### ISSUE TITLE
Not able to use a wallet in a function call

### ISSUE THREAD

**Issue by ccarnino** [Shard-Labs/starknet-hardhat-plugin#64]
Hello again and sorry for writing all the time.

I have previously deployed on devnet a wallet on called `Deployer` with success:
```
Contract address: 0x0227353702c3b2f0058f537095ae90b77ecef173ba6f4199dce78b792fc97652
Public key: 0x02f56dc23f579d14801c645c48d28d39352ac47cd7dea3d0a1f8967a61dc2dd7
```

I deployed a contract with success:
```
yarn hardhat starknet-deploy ERC721_pokianimals \
  --starknet-network devnet \
  --inputs "1349479273 1347373897 0x02f56dc23f579d14801c645c48d28d39352ac47cd7dea3d0a1f8967a61dc2dd7"

Deploy transaction was sent.
Contract address: 0x01d3e84687fd354e2e6c615c816f319188a7fb2bb91553f2f2f5bd2c1eaea57f
Transaction hash: 0x01b9b825267180fadf3f0b4b164622ad3058a32d1fbed1be4f9ffa139e3e6cc6
```

When I call a function which does not require wallet, I get a success (123 0):
```
❯ yarn hardhat starknet-call \
  --starknet-network devnet \
  --contract ERC721_pokianimals \
  --address 0x01d3e84687fd354e2e6c615c816f319188a7fb2bb91553f2f2f5bd2c1eaea57f \
  --function registration_price  

123 0

        Succeeded
✨  Done in 3.10s.
```

When I try to call the same function which requires a wallet, or for the sake of example even the same one, I get a 500 error:
```
❯ yarn hardhat starknet-call \
  --starknet-network devnet \
  --contract ERC721_pokianimals \
  --address 0x01d3e84687fd354e2e6c615c816f319188a7fb2bb91553f2f2f5bd2c1eaea57f \
  --function registration_price \
  --wallet Deployer

Starknet plugin using the active environment.
Got BadRequest
Traceback (most recent call last):
  File "/Users/claudio/cairo_venv/lib/python3.9/site-packages/services/external_api/base_client.py", line 116, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 500. Text: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Error: BadRequest: HTTP error ocurred. Status: 500. Text: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

        Failed
```

Happens the same when invoking a function.

I think that the issue is with this plugin or starknet-devnet. I have deployed the same contract on [alpha-goerli](https://goerli.voyager.online/contract/0x03f484dc8e92a1aa14f4a96af4b9238b827f17228a64444cace25bffa6dac17f#readContract) and it works correctly.

Ideas?

Thanks a lot for the support! 🙌

**Comment by dribeiro-ShardLabs** [comment]
Hi @ccarnino 

The issue is that the OpenZeppelin Account.cairo contract that the cairo-lang package uses for the wallet feature is an older version that specifies the `@raw_output` decorator for the `execute` function, something that's not supported in devnet yet due to limitations in the Starknet testing framework, namely the argument parser, which does not allow the `@raw_output` response structure.

![imagem](https://user-images.githubusercontent.com/94369106/155678420-63d608ba-6060-419b-ba8c-7049e7887f1e.png)

We will be releasing soon a new version of the plugin introducing another way of interacting with Accounts that will work in devnet as well :)

**Comment by ccarnino** [comment]
Thank you a lot for the explanation!

**Comment by ccarnino** [comment]
Just to confirm, this fix was not supposed to be shipped with the account changes of the new 0.4.2 release right?

**Comment by dribeiro-ShardLabs** [comment]
Hi @ccarnino ,

No, this is something internal to starknet, and I think it should be fixed in the next cairo-lang release.
The Account feature in the new release of the plugin is a different way of using accounts to interact  with Starknet contracts

**Comment by ccarnino** [comment]
thanks for the clarification
